BookBird/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.core import views
from apps.core.views import IndexView


urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
    path("admin/", admin.site.urls),
    path(
        "authors/",
        include("apps.authors.urls"),
    ),
    path(
        "publications/",
        include("apps.publications.urls"),
    ),
    path(
        "titles/",
        include("apps.titles.urls"),
    ),  # Keep titles URLs for detail views
    path(
        "accounts/",
        include("apps.accounts.urls"),
    ),
    path(
        "lists/",
        include("apps.lists.urls"),
    ),
    path(
        "friends/",
        include("apps.friends.urls"),
    ),
    path(
        "search/",
        views.GlobalSearchView.as_view(),
        name="search",
    ),
    path(
        "reviews/",
        include("apps.reviews.urls"),
    ),
    path(
        "groups/",
        include("apps.groups.urls"),
    ),
    path(
        "awards/",
        include("apps.awards.urls"),
    ),
]

apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page="index"),
        name="logout",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "profile/edit/",
        views.ProfileUpdateView.as_view(),
        name="profile_edit",
    ),
    path(
        "password/change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
]

apps/accounts/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile",
    )

    nickname = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        unique=True,
        verbose_name=_("Nickname"),
        help_text=_("Your preferred display name"),
    )

    birth_date = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Birth Date"),
        help_text=_("Your date of birth"),
    )

    country = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name=_("Country"),
        help_text=_("Your country of residence"),
    )

    bio = models.TextField(
        blank=True,
        null=True,
        verbose_name=_("Biography"),
        help_text=_("Tell us about yourself"),
    )

    avatar = models.URLField(
        blank=True,
        null=True,
        verbose_name=_("Avatar URL"),
        help_text=_("URL to your profile picture"),
    )

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ["user__username"]
        indexes = [
            models.Index(fields=["user"]),
        ]

    def __str__(self):
        return self.user.get_full_name() or self.user.username

    def clean(self):
        super().clean()
        if self.birth_date and self.birth_date > timezone.now().date():
            raise ValidationError(_("Birth date cannot be in the future"))

        if self.birth_date and self.birth_date.year < 1900:
            raise ValidationError(
                {"birth_date": _("Birth date year cannot be before 1900.")}
            )
        if self.nickname:
            # Check for forbidden words
            forbidden_words = ["admin", "root", "system"]  # Example list
            if self.nickname.lower() in forbidden_words:
                raise ValidationError({"nickname": _("This nickname is not allowed.")})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.profile.save()
    except UserProfile.DoesNotExist:
        UserProfile.objects.create(user=instance)

apps/accounts/forms.py
from django.utils import timezone
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your email"),
            }
        ),
    )
    nickname = forms.CharField(
        required=False,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your nickname"),
            }
        ),
    )
    birth_date = forms.DateField(
        required=False,
        widget=forms.DateInput(
            attrs={
                "class": "form-control",
                "type": "date",
                "placeholder": _("Enter your birth date"),
            }
        ),
    )
    country = forms.CharField(
        required=False,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Enter your country"),
            }
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "nickname",
            "birth_date",
            "country",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {
                    "class": "form-control",
                }
            )
            if field in self.errors:
                self.fields[field].widget.attrs.update(
                    {"class": "form-control is-invalid"}
                )

    def clean_nickname(self):
        nickname = self.cleaned_data.get("nickname")
        if nickname and UserProfile.objects.filter(nickname=nickname).exists():
            raise forms.ValidationError(_("This nickname is already taken."))
        return nickname

    def clean_birth_date(self):
        birth_date = self.cleaned_data.get("birth_date")
        if birth_date and birth_date > timezone.now().date():
            raise forms.ValidationError(_("Birth date cannot be in the future."))
        return birth_date

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
            user.profile.nickname = self.cleaned_data["nickname"]
            user.profile.birth_date = self.cleaned_data["birth_date"]
            user.profile.country = self.cleaned_data["country"]
            user.profile.save()
        return user


class ProfileUpdateForm(forms.ModelForm):
    nickname = forms.CharField(
        required=False,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Choose a nickname"),
            }
        ),
    )
    birth_date = forms.DateField(
        required=False,
        widget=forms.DateInput(
            attrs={
                "class": "form-control",
                "type": "date",
            }
        ),
    )
    country = forms.CharField(
        required=False,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Your country"),
            }
        ),
    )
    bio = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "rows": 4,
                "placeholder": _("Tell us about yourself"),
            }
        ),
    )
    avatar = forms.URLField(
        required=False,
        widget=forms.URLInput(
            attrs={
                "class": "form-control",
                "placeholder": _("URL to your profile picture"),
            }
        ),
    )

    class Meta:
        model = UserProfile
        fields = (
            "nickname",
            "birth_date",
            "country",
            "bio",
            "avatar",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            if field in self.errors:
                field.widget.attrs["class"] = "form-control is-invalid"

    def clean(self):
        cleaned_data = super().clean()
        if avatar_url := cleaned_data.get("avatar"):
            if not avatar_url.startswith(("http://", "https://")):
                self.add_error("avatar", _("Please enter a valid URL"))
        return cleaned_data


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Username"),
            }
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": _("Password"),
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update(
                {"class": "form-control", "placeholder": field.label}
            )

    def clean_new_password2(self):
        password2 = super().clean_new_password2()
        password1 = self.cleaned_data.get("new_password1")
        if password1 and password2 and password1 != password2:
            self.add_error("new_password2", _("The two password fields didn't match."))
        return password2

apps/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import SignUpForm, LoginForm, ProfileUpdateForm, CustomPasswordChangeForm
from .models import UserProfile
from django.utils.translation import gettext_lazy as _


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response


class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    redirect_authenticated_user = True


class ProfileView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    template_name = "accounts/profile.html"
    fields = ["nickname", "birth_date", "country", "bio", "avatar"]

    def get_object(self, queryset=None):
        return self.request.user.profile


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = ProfileUpdateForm
    template_name = "accounts/profile_update.html"
    success_url = reverse_lazy("accounts:profile")

    def get_object(self, queryset=None):
        return self.request.user.profile


class PasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = "accounts/password_change.html"
    success_url = reverse_lazy("accounts:profile")
    success_message = _("Your password was successfully updated!")

templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-header bg-primary bg-gradient text-white py-3">
                    <h4 class="card-title mb-0">{% trans "Sign In" %}</h4>
                </div>
                <div class="card-body p-4">
                    <form method="post" novalidate class="auth-form">
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger mb-4">
                                {% for error in form.non_field_errors %}
                                    <div class="d-flex align-items-center">
                                        <i class="bi bi-exclamation-triangle-fill me-2"></i>
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="form-group mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold mb-2">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="text-danger ms-1">*</span>
                                    {% endif %}
                                </label>
                                <div class="input-group {% if field.errors %}has-validation{% endif %}">
                                    <span class="input-group-text">
                                        <i class="bi {% if field.name == 'username' %}bi-person
                                                    {% elif 'password' in field.name %}bi-lock
                                                    {% else %}bi-pencil{% endif %} text-primary">
                                        </i>
                                    </span>
                                    {{ field }}
                                </div>
                                {% if field.errors %}
                                    <div class="error-messages mt-1">
                                        {% for error in field.errors %}
                                            <small class="text-danger d-block">
                                                <i class="bi bi-exclamation-circle me-1"></i>
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                {% if field.help_text %}
                                    <div class="form-text text-muted small mt-1">
                                        <i class="bi bi-info-circle me-1"></i>
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 py-2 mt-3">
                            <i class="bi bi-box-arrow-in-right me-2"></i>{% trans "Sign In" %}
                        </button>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    {% trans "Don't have an account?" %}
                    <a href="{% url 'accounts:signup' %}" class="text-decoration-none">
                        {% trans "Sign Up" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-header bg-primary bg-gradient text-white py-3">
                    <h4 class="card-title mb-0">{% trans "Change Password" %}</h4>
                </div>
                <div class="card-body p-4">
                    <form method="post" novalidate class="auth-form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold mb-2">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="text-danger ms-1">*</span>
                                    {% endif %}
                                </label>
                                <div class="input-group {% if field.errors %}has-validation{% endif %}">
                                    <span class="input-group-text">
                                        <i class="bi bi-lock text-primary"></i>
                                    </span>
                                    {{ field }}
                                </div>
                                {% if field.errors %}
                                    <div class="error-messages mt-1">
                                        {% for error in field.errors %}
                                            <small class="text-danger d-block">
                                                <i class="bi bi-exclamation-circle me-1"></i>
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                {% if field.help_text %}
                                    <div class="form-text text-muted small mt-1">
                                        <i class="bi bi-info-circle me-1"></i>
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 py-2 mt-3">
                            <i class="bi bi-check2-circle me-2"></i>{% trans "Change Password" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary bg-gradient text-white py-3 d-flex justify-content-between align-items-center">
                        <h4 class="card-title mb-0">{% trans "Profile" %}</h4>
                        <div>
                            <a href="{% url 'accounts:password_change' %}" class="btn btn-light btn-sm me-2">
                                <i class="bi bi-lock"></i> {% trans "Change Password" %}
                            </a>
                            <a href="{% url 'accounts:profile_edit' %}" class="btn btn-light btn-sm">
                                <i class="bi bi-pencil"></i> {% trans "Edit Profile" %}
                            </a>
                        </div>
                    </div>
                    <div class="card-body p-4">
                        <div class="text-center mb-4">
                            {% if user.profile.avatar %}
                                <img src="{{ user.profile.avatar }}"
                                     alt="{% trans 'Profile picture' %}"
                                     class="rounded-circle mb-3"
                                     style="width: 128px; height: 128px; object-fit: cover;"
                                     onerror="this.src='https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'">
                            {% else %}
                                <img src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png"
                                     alt="{% trans 'Default profile picture' %}"
                                     class="rounded-circle mb-3"
                                     style="width: 128px; height: 128px; object-fit: cover;">
                            {% endif %}
                            <h5 class="mb-0">{{ user.profile.nickname|default:user.username }}</h5>
                            <p class="text-muted">{{ user.email }}</p>
                        </div>

                        <div class="profile-info">
                            {% if user.profile.birth_date %}
                                <div class="mb-3">
                                    <i class="bi bi-calendar text-primary"></i>
                                    <strong>{% trans "Birth Date" %}:</strong>
                                    {{ user.profile.birth_date }}
                                </div>
                            {% endif %}

                            {% if user.profile.country %}
                                <div class="mb-3">
                                    <i class="bi bi-globe text-primary"></i>
                                    <strong>{% trans "Country" %}:</strong>
                                    {{ user.profile.country }}
                                </div>
                            {% endif %}

                            {% if user.profile.bio %}
                                <div class="mb-3">
                                    <i class="bi bi-person-lines-fill text-primary"></i>
                                    <strong>{% trans "Bio" %}:</strong>
                                    <p class="mt-2">{{ user.profile.bio }}</p>
                                </div>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/profile_update.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Update Profile" %}{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-header bg-primary bg-gradient text-white py-3">
                    <h4 class="card-title mb-0">{% trans "Update Profile" %}</h4>
                </div>
                <div class="card-body p-4">
                    <form method="post" novalidate class="auth-form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold mb-2">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="text-danger ms-1">*</span>
                                    {% endif %}
                                </label>
                                <div class="input-group {% if field.errors %}has-validation{% endif %}">
                                    <span class="input-group-text">
                                        <i class="bi {% if field.name == 'nickname' %}bi-tag
                                                    {% elif field.name == 'birth_date' %}bi-calendar
                                                    {% elif field.name == 'country' %}bi-globe
                                                    {% elif field.name == 'bio' %}bi-pencil-square
                                                    {% elif field.name == 'avatar' %}bi-image
                                                    {% else %}bi-pencil{% endif %} text-primary">
                                        </i>
                                    </span>
                                    {{ field }}
                                </div>
                                {% if field.errors %}
                                    <div class="error-messages mt-1">
                                        {% for error in field.errors %}
                                            <small class="text-danger d-block">
                                                <i class="bi bi-exclamation-circle me-1"></i>
                                                {{ error }}
                                            </small>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                                {% if field.help_text %}
                                    <div class="form-text text-muted small mt-1">
                                        <i class="bi bi-info-circle me-1"></i>
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 py-2 mt-3">
                            <i class="bi bi-check2-circle me-2"></i>{% trans "Save Changes" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Sign Up" %}{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card shadow-sm">
                <div class="card-header bg-primary bg-gradient text-white py-3">
                    <h4 class="card-title mb-0">{% trans "Sign Up" %}</h4>
                </div>
                <div class="card-body p-4">
                    <form method="post" novalidate class="auth-form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold mb-2">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="text-danger ms-1">*</span>
                                    {% endif %}
                                </label>
                                <div class="input-group {% if field.errors %}has-validation{% endif %}">
                                    <span class="input-group-text">
                                        <i class="bi {% if field.name == 'username' %}bi-person
                                                    {% elif field.name == 'email' %}bi-envelope
                                                    {% elif 'password' in field.name %}bi-lock
                                                    {% elif field.name == 'nickname' %}bi-tag
                                                    {% elif field.name == 'birth_date' %}bi-calendar
                                                    {% elif field.name == 'country' %}bi-globe
                                                    {% else %}bi-pencil{% endif %} text-primary">
                                        </i>
                                    </span>
                                    {{ field }}
                                    {% if field.errors %}
                                        <div class="invalid-tooltip">
                                            {% for error in field.errors %}
                                                {{ error }}{% if not forloop.last %}<br>{% endif %}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>
                                {% if field.help_text %}
                                    <div class="form-text text-muted small mt-1">
                                        <i class="bi bi-info-circle me-1"></i>
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100 py-2 mt-3">
                            <i class="bi bi-person-plus me-2"></i>{% trans "Sign Up" %}
                        </button>
                    </form>
                </div>
                <div class="card-footer text-center py-3">
                    {% trans "Already have an account?" %}
                    <a href="{% url 'accounts:login' %}" class="text-decoration-none">
                        {% trans "Sign In" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}